### PR TITLE
Using NVM instead of Node.js globally

### PR DESCRIPTION
**Pull request by maratfakhreev**

### CODE REVIEW

**Comment by timurvafin** [comment]
@maratfakhreev please fix tests

**Comment by timurvafin** [comment]
@maratfakhreev any help needed?

**Comment by maratfakhreev** [comment]
@timurvafin Yeah, need help. I configured CI for testing only node module and tried a lot of fixes but nothing helped. I only has understood that trouble connected with `source "$(brew --prefix nvm)/nvm.sh"` line

**Comment by timurvafin** [comment]
@maratfakhreev please review

**Comment by maratfakhreev** [comment]
@timurvafin awesome) looks perfectly. :+1:

**Pull request merged**
