### PR TITLE
Check software updates

### PR DESCRIPTION
**Pull request by ilyasgaraev**

### CODE REVIEW

**Comment by timurvafin** [comment]
@fsgaraev could you please provide some background what's wrong with current implementation?

**Comment by arkadiybutermanov** [comment]
@timurvafin there was an issue when I've tried to use osx-bootstrap.

On my home machine: it failed two times with "Itunes Installation failed. Unknown error", on the third time it run without any problem.
On my work machine: it failed one time with the same error. Then I tried to install updates manually (from AppStore). It succeded.

Looks like the issue is happenning randomly, and there is no way to reproduce it other than installing real updates on real Mac. 

I think it's better to Ask users for manual update rather than failing with untraceable error.

**Comment by timurvafin** [comment]
@ilyasgaraev @arkadiybutermanov could that issue be related only for some osx versions? 
For example this issue appears only when we update from 10.10.3 to 10.10.4?

**Comment by timurvafin** [comment]
Could not reproduce issue any more.

**Pull request closed without merging**
